development:
  bucket: unigleam-dev
  access_key_id: 'AKIAJBOIRFKMQTJT6T6Q'
  secret_access_key: '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'
  region: 'ap-northeast-1'

production:
  bucket: unigleam-pro
  access_key_id: 'AKIAJBOIRFKMQTJT6T6Q'
  secret_access_key: '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'
  region: 'ap-northeast-1'
